#! /bin/bash

# funcs
program_installed() {
  [ -x "$(which $1)" ]
}

# install libs
if program_installed apt-get ; then apt-get install ruby rubygems p7zip-full
elif program_installed yum ; then yum install ruby rubygems p7zip-full
elif program_installed brew ; then brew install ruby p7zip
else
  echo 'No package manager available, please install the following manually: ruby rubygems p7zip-full'
  exit 2
fi

# install bundler
gem install bundler

# install gems
bundle install
